// <auto-generated />
using FishesApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FishesApi.Migrations
{
    [DbContext(typeof(FishContext))]
    [Migration("20240430014919_PlaceInFish")]
    partial class PlaceInFish
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FishesApi.Models.Fish", b =>
                {
                    b.Property<int>("FishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FishId"));

                    b.Property<int>("FishCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("FishColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FishDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FishLength")
                        .HasColumnType("int");

                    b.Property<string>("FishName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FishWeight")
                        .HasColumnType("int");

                    b.Property<string>("PlaceOfCapture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FishId");

                    b.HasIndex("FishCategoryId");

                    b.ToTable("Fishes");
                });

            modelBuilder.Entity("FishesApi.Models.FishCategory", b =>
                {
                    b.Property<int>("FishCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FishCategoryId"));

                    b.Property<string>("FishCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FishCategoryId");

                    b.ToTable("FishCategories");
                });

            modelBuilder.Entity("FishesApi.Models.Fish", b =>
                {
                    b.HasOne("FishesApi.Models.FishCategory", "FishCategory")
                        .WithMany()
                        .HasForeignKey("FishCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FishCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
