//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TREST_RESERVACION
    {
        public int TN_NumReservacion { get; set; }
        public int TN_IdCliente { get; set; }
        public int TN_IdMesa { get; set; }
        public int TN_IdMenu { get; set; }
        public int TN_Cantidad { get; set; }
        public System.DateTime TF_FecReserva { get; set; }
    
        public virtual TREST_CLIENTES TREST_CLIENTES { get; set; }
        public virtual TREST_MENU TREST_MENU { get; set; }
        public virtual TREST_MESAS TREST_MESAS { get; set; }
    }
}
