//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TREST_CLIENTES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TREST_CLIENTES()
        {
            this.TREST_RESERVACION = new HashSet<TREST_RESERVACION>();
        }
    
        public int TN_IdCliente { get; set; }
        public string TC_Nombre { get; set; }
        public string TC_Ap1 { get; set; }
        public string TC_Ap2 { get; set; }
        public string Tc_NumTelefonico { get; set; }
        public string TC_CorreoElectronico { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TREST_RESERVACION> TREST_RESERVACION { get; set; }
    }
}
