//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazUsuario.ReferenciaSrvSeguridad {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TUSR_USUARIOS", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class TUSR_USUARIOS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TC_ContrasenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TC_UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InterfazUsuario.ReferenciaSrvSeguridad.TUSR_PERFILES[] TUSR_PERFILESField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TC_Contrasena {
            get {
                return this.TC_ContrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.TC_ContrasenaField, value) != true)) {
                    this.TC_ContrasenaField = value;
                    this.RaisePropertyChanged("TC_Contrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TC_Usuario {
            get {
                return this.TC_UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.TC_UsuarioField, value) != true)) {
                    this.TC_UsuarioField = value;
                    this.RaisePropertyChanged("TC_Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InterfazUsuario.ReferenciaSrvSeguridad.TUSR_PERFILES[] TUSR_PERFILES {
            get {
                return this.TUSR_PERFILESField;
            }
            set {
                if ((object.ReferenceEquals(this.TUSR_PERFILESField, value) != true)) {
                    this.TUSR_PERFILESField = value;
                    this.RaisePropertyChanged("TUSR_PERFILES");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TUSR_PERFILES", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class TUSR_PERFILES : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TC_NomPerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TN_PerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InterfazUsuario.ReferenciaSrvSeguridad.TUSR_USUARIOS[] TUSR_USUARIOSField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TC_NomPerfil {
            get {
                return this.TC_NomPerfilField;
            }
            set {
                if ((object.ReferenceEquals(this.TC_NomPerfilField, value) != true)) {
                    this.TC_NomPerfilField = value;
                    this.RaisePropertyChanged("TC_NomPerfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TN_Perfil {
            get {
                return this.TN_PerfilField;
            }
            set {
                if ((this.TN_PerfilField.Equals(value) != true)) {
                    this.TN_PerfilField = value;
                    this.RaisePropertyChanged("TN_Perfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InterfazUsuario.ReferenciaSrvSeguridad.TUSR_USUARIOS[] TUSR_USUARIOS {
            get {
                return this.TUSR_USUARIOSField;
            }
            set {
                if ((object.ReferenceEquals(this.TUSR_USUARIOSField, value) != true)) {
                    this.TUSR_USUARIOSField = value;
                    this.RaisePropertyChanged("TUSR_USUARIOS");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PA_recPerfilesXUsuario_Result", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class PA_recPerfilesXUsuario_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TC_UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TN_PerfilField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TC_Usuario {
            get {
                return this.TC_UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.TC_UsuarioField, value) != true)) {
                    this.TC_UsuarioField = value;
                    this.RaisePropertyChanged("TC_Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TN_Perfil {
            get {
                return this.TN_PerfilField;
            }
            set {
                if ((this.TN_PerfilField.Equals(value) != true)) {
                    this.TN_PerfilField = value;
                    this.RaisePropertyChanged("TN_Perfil");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReferenciaSrvSeguridad.IsrvSeguridad")]
    public interface IsrvSeguridad {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvSeguridad/recUsuario", ReplyAction="http://tempuri.org/IsrvSeguridad/recUsuarioResponse")]
        InterfazUsuario.ReferenciaSrvSeguridad.TUSR_USUARIOS recUsuario(string pLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvSeguridad/recUsuario", ReplyAction="http://tempuri.org/IsrvSeguridad/recUsuarioResponse")]
        System.Threading.Tasks.Task<InterfazUsuario.ReferenciaSrvSeguridad.TUSR_USUARIOS> recUsuarioAsync(string pLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvSeguridad/recPerfilesPorUsuario", ReplyAction="http://tempuri.org/IsrvSeguridad/recPerfilesPorUsuarioResponse")]
        InterfazUsuario.ReferenciaSrvSeguridad.PA_recPerfilesXUsuario_Result[] recPerfilesPorUsuario(string pLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvSeguridad/recPerfilesPorUsuario", ReplyAction="http://tempuri.org/IsrvSeguridad/recPerfilesPorUsuarioResponse")]
        System.Threading.Tasks.Task<InterfazUsuario.ReferenciaSrvSeguridad.PA_recPerfilesXUsuario_Result[]> recPerfilesPorUsuarioAsync(string pLogin);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IsrvSeguridadChannel : InterfazUsuario.ReferenciaSrvSeguridad.IsrvSeguridad, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsrvSeguridadClient : System.ServiceModel.ClientBase<InterfazUsuario.ReferenciaSrvSeguridad.IsrvSeguridad>, InterfazUsuario.ReferenciaSrvSeguridad.IsrvSeguridad {
        
        public IsrvSeguridadClient() {
        }
        
        public IsrvSeguridadClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IsrvSeguridadClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvSeguridadClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvSeguridadClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public InterfazUsuario.ReferenciaSrvSeguridad.TUSR_USUARIOS recUsuario(string pLogin) {
            return base.Channel.recUsuario(pLogin);
        }
        
        public System.Threading.Tasks.Task<InterfazUsuario.ReferenciaSrvSeguridad.TUSR_USUARIOS> recUsuarioAsync(string pLogin) {
            return base.Channel.recUsuarioAsync(pLogin);
        }
        
        public InterfazUsuario.ReferenciaSrvSeguridad.PA_recPerfilesXUsuario_Result[] recPerfilesPorUsuario(string pLogin) {
            return base.Channel.recPerfilesPorUsuario(pLogin);
        }
        
        public System.Threading.Tasks.Task<InterfazUsuario.ReferenciaSrvSeguridad.PA_recPerfilesXUsuario_Result[]> recPerfilesPorUsuarioAsync(string pLogin) {
            return base.Channel.recPerfilesPorUsuarioAsync(pLogin);
        }
    }
}
