//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Entidades;
    
    public partial class EntidadesRestaurante : DbContext
    {
        public EntidadesRestaurante()
            : base("name=EntidadesRestaurante")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TREST_CLIENTES> TREST_CLIENTES { get; set; }
        public virtual DbSet<TREST_MENU> TREST_MENU { get; set; }
        public virtual DbSet<TREST_MESAS> TREST_MESAS { get; set; }
        public virtual DbSet<TREST_RESERVACION> TREST_RESERVACION { get; set; }
        public virtual DbSet<TREST_TIPOMENU> TREST_TIPOMENU { get; set; }
    }
}
